### ISSUE TITLE
appBar clashes with statusBar color and SystemUI elements

### ISSUE THREAD

**Issue by Rochan-A** [MEC-Enigma/MEC-CPMA#1]
Adding an appBar in the Material app Scaffold overrides the statusBar and systemUI elements config in `main.dart`.

**Comment by Manikumar1998** [comment]
`main.dart` displays the `mec_page.dart` page. I don't see any problem in adding an Appbar to `mec_page.dart`. Can you elaborate?

**Comment by Manikumar1998** [comment]
fa

**Comment by Manikumar1998** [comment]
`Colors.transparent` is a transparent layer. You will see the appBar's color, change it to some other color like `Colors.red` the status bar will change. Is it just about the color of the status bar or anything else?

**Comment by Rochan-A** [comment]
To get a full screen effect like this 
![options](https://user-images.githubusercontent.com/9353539/41497749-4a490cf4-7179-11e8-8f0f-095fefa99b91.png)

**Comment by Rochan-A** [comment]
This  [pr](https://github.com/MEC-Enigma/MEC-CPMA/pull/2) fixes it for now
